<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DefaultDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('activities')->insertOrIgnore([
            [
                'id' => 1,
                'name' => 'Kayak',
                'description_fr' => "Les sorties guidées et la location de kayak de mer sont pour une clientèle de 18 ans et +, ou 12 ans et + si accompagné d'un adulte dans un kayak en tandem.\nSVP, noter que cette activité ne s'adresse pas aux jeunes enfants.",
                'description_en' => null,
                'rules_fr' => "Les sorties guidées et la location sont pour une clientèle de 18 ans et +, ou 12 ans et + si accompagné d'un adulte dans un kayak en tandem.\nSVP, noter que cette activité ne s'adresse pas aux jeunes enfants.\nIl faudra vous munir de vêtement de sport approprié, d'un chapeau et de crème solaire. La Route de Champlain s'assure de pouvoir vous fournir des vestes de sauvetage.\nIl faudra vous munir d'une gourde d'eau et d'un goûter léger (collations, barre d'énergie, etc.). Aucune nourriture n'est vendu sur nos sites. Il sera possible de remplir vos bouteilles d'eau.",
                'rules_en' => null,
            ],
        ]);

        DB::table('boat_categories')->insertOrIgnore([
            [
                'id' => 1,
                'name' => 'Kayak',
                'image' => 'boatCategoriesImages/kayak_solo.png',
                'total_capacity' => 1,
                'teen_capacity' => 0,
                'child_capacity' => 0,
                'minimum_booking_person'=>1,
                'activity_id'=>1,
                'description_fr'=>'Kayak de mer à une place.',
            ],
            [
                'id' => 2,
                'name' => 'Bateau électrique',
                'image' => 'boatCategoriesImages/fantail.jpg',
                'total_capacity' => 9,
                'teen_capacity' => 8,
                'child_capacity' => 7,
                'minimum_booking_person'=>2,
                'activity_id'=>null,
                'description_fr'=>'Fantail 9 places',
            ],
            [
                'id' => 3,
                'name' => 'Rabaska',
                'image' => 'boatCategoriesImages/rabaska.jpg',
                'total_capacity' => 15,
                'teen_capacity' => 14,
                'child_capacity' => 13,
                'minimum_booking_person'=>6,
                'activity_id'=>null,
                'description_fr'=>'Gros canot 16 places',
            ],
            [
                'id' => 4,
                'name' => 'Voile-aviron',
                'image' => null,
                'total_capacity' => 9,
                'teen_capacity' => 8,
                'child_capacity' => 7,
                'minimum_booking_person'=>2,
                'activity_id'=>null,
                'description_fr'=>'Embarcation à rame et à voile de 10 places.',
            ],
            [
                'id' => 5,
                'name' => 'Kayak tandem',
                'image' => 'boatCategoriesImages/kayak_tandem.jpg',
                'total_capacity' => 2,
                'teen_capacity' => 1,
                'child_capacity' => 0,
                'minimum_booking_person'=>2,
                'activity_id'=>1,
                'description_fr'=>'Kayak de mer à deux places, plus stable que le kayak solo.',
            ],
        ]);

        DB::table('promotions')->insertOrIgnore([
            [
                'name'=>'Tour gratuit',
                'products_id'=>json_encode([5, 19]),
                'value'=>100,
                'is_percentage'=>true,
                'is_on_client'=>true,

            ],
        ]);

        DB::table('subscriptions')->insertOrIgnore([
            [
                'name'=>'Membre',
                'price'=>20,
                'duration'=>365,
                'add_promotion_id'=>1,
                'is_taxable'=>false,
                'permits_boarding'=>false,
                'boat_categories_id'=>null,
                'is_rental'=>null,
                'max_passenger'=>null,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'is_full_boat'=>null,
                'fiscal_year_expiry'=>true,
            ],
            [
                'name'=>'Kayak illimité sans guide',
                'price'=>70,
                'duration'=>31,
                'add_promotion_id'=>null,
                'is_taxable'=>true,
                'permits_boarding'=>true,
                'boat_categories_id'=>json_encode([1, 5]),
                'is_rental'=>true,
                'max_passenger'=>1,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'is_full_boat'=>false,
                'fiscal_year_expiry'=>false,
            ],
            [
                'name'=>'Kayak illimité avec guide',
                'price'=>100,
                'duration'=>31,
                'add_promotion_id'=>null,
                'is_taxable'=>true,
                'permits_boarding'=>true,
                'boat_categories_id'=>json_encode([1, 5]),
                'is_rental'=>false,
                'max_passenger'=>1,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'is_full_boat'=>false,
                'fiscal_year_expiry'=>false,
            ],
        ]);

        DB::table('products')->insertOrIgnore([
            [
                'id' => 2,
                'name' => 'Kayak guidé',
                'price' => 20.0000,
                'boat_category_id' => 1,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 1,
                'required_subscription_id' => null,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:38:30.000Z',
                'updated_at' => '2019-07-10T00:29:23.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Kayak guidé [Membre]',
                'price' => 15.0000,
                'boat_category_id' => 1,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 1,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => json_encode([2]),
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:49:28.000Z',
                'updated_at' => '2019-07-10T00:27:29.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'kayak guidé',
                'price' => 35.0000,
                'boat_category_id' => 1,
                'duration' => 120,
                'is_rental' => 0,
                'is_initiation' => 1,
                'required_subscription_id' => null,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:53:46.000Z',
                'updated_at' => '2019-07-10T00:27:36.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'kayak guidé [Membre]',
                'price' => 25.0000,
                'boat_category_id' => 1,
                'duration' => 120,
                'is_rental' => 0,
                'is_initiation' => 1,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => json_encode([6]),
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:54:09.000Z',
                'updated_at' => '2019-07-10T00:27:55.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'kayak guidé',
                'price' => 40.0000,
                'boat_category_id' => 1,
                'duration' => 180,
                'is_rental' => 0,
                'is_initiation' => 1,
                'required_subscription_id' => null,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:54:45.000Z',
                'updated_at' => '2019-05-29T03:54:45.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'kayak guidé [Membre]',
                'price' => 30.0000,
                'boat_category_id' => 1,
                'duration' => 180,
                'is_rental' => 0,
                'is_initiation' => 1,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => json_encode([8]),
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:55:09.000Z',
                'updated_at' => '2019-05-29T03:55:09.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'kayak location',
                'price' => 10.0000,
                'boat_category_id' => 1,
                'duration' => 60,
                'is_rental' => 1,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:55:52.000Z',
                'updated_at' => '2019-05-29T03:55:52.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'kayak location',
                'price' => 20.0000,
                'boat_category_id' => 1,
                'duration' => 120,
                'is_rental' => 1,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:56:10.000Z',
                'updated_at' => '2019-05-29T03:56:10.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'kayak location',
                'price' => 25.0000,
                'boat_category_id' => 1,
                'duration' => 180,
                'is_rental' => 1,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:56:28.000Z',
                'updated_at' => '2019-05-29T03:56:28.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'Rabaska guidé',
                'price' => 40.0000,
                'boat_category_id' => 3,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => null,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 15,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:57:43.000Z',
                'updated_at' => '2019-05-29T03:57:43.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'Rabaska guidé [Membre]',
                'price' => 30.0000,
                'boat_category_id' => 3,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => json_encode([13]),
                'max_passenger' => 15,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:58:03.000Z',
                'updated_at' => '2019-05-29T03:58:03.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'Rabaska Location',
                'price' => 20.0000,
                'boat_category_id' => 3,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 15,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:58:54.000Z',
                'updated_at' => '2019-05-29T03:58:54.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'Fantail nolisé',
                'price' => 120.0000,
                'boat_category_id' => 2,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => null,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 9,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:59:26.000Z',
                'updated_at' => '2019-05-29T03:59:26.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'Fantail nolisé [Membre]',
                'price' => 80.0000,
                'boat_category_id' => 2,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => json_encode([16]),
                'max_passenger' => 9,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T03:59:45.000Z',
                'updated_at' => '2019-05-29T03:59:45.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Fantail',
                'price' => 15.0000,
                'boat_category_id' => 2,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => null,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T04:02:10.000Z',
                'updated_at' => '2019-05-29T04:02:10.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'Fantail [Membre]',
                'price' => 10.0000,
                'boat_category_id' => 2,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => json_encode([18]),
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T04:02:29.000Z',
                'updated_at' => '2019-05-29T04:02:29.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'Enfant Fantail',
                'price' => 7.5000,
                'boat_category_id' => 2,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => null,
                'required_products_id' => json_encode([18]),
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => true,
                'is_teen'=>false,
                'is_adult'=>false,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-05-29T04:49:48.000Z',
                'updated_at' => '2019-06-04T14:54:15.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'Enfant Fantail [Membre]',
                'price' => 5.0000,
                'boat_category_id' => 2,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => json_encode([19]),
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => true,
                'is_teen'=>false,
                'is_adult'=>false,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-06-04T15:42:33.000Z',
                'updated_at' => '2019-06-05T02:07:56.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'Enfant Kayak Gratuit',
                'price' => 0.0000,
                'boat_category_id' => 1,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => null,
                'required_products_id' => json_encode([2, 5, 6, 7, 8, 9, 10, 11, 12]),
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => true,
                'is_teen'=>false,
                'is_adult'=>false,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-06-04T15:43:58.000Z',
                'updated_at' => '2019-06-05T02:04:34.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'name' => 'Forfait Pique-Nique',
                'price' => 100.0000,
                'boat_category_id' => 2,
                'duration' => 120,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 9,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2019-06-04T16:19:14.000Z',
                'updated_at' => '2019-06-04T16:19:14.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'name' => 'Offre Spéciale',
                'price' => 20.0000,
                'boat_category_id' => 2,
                'duration' => 120,
                'is_rental' => 0,
                'is_initiation' => 0,
                'required_subscription_id' => 1,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 1,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([]),
                'created_at' => '2019-06-04T16:19:45.000Z',
                'updated_at' => '2019-06-04T16:19:45.000Z',
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'name' => 'Tandem guidé',
                'price' => 40.0000,
                'boat_category_id' => 5,
                'duration' => 60,
                'is_rental' => 0,
                'is_initiation' => 1,
                'required_subscription_id' => null,
                'required_products_id' => null,
                'replace_products_id' => null,
                'max_passenger' => 2,
                'is_taxable' => 1,
                'is_child' => false,
                'is_teen'=>true,
                'is_adult'=>true,
                'available_points_of_sale_ids'=>json_encode([1, 2, 3]),
                'created_at' => '2021-06-04T16:19:45.000Z',
                'updated_at' => '2021-06-04T16:19:45.000Z',
                'deleted_at' => null,
            ],
        ]);
    }
}
