<?php

namespace Database\Seeders;

use App\Models\Trip;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ScheduleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('calendars')->insertOrIgnore([
            [
                'id' => 1,
                'name' => 'Lundi et mercredi',
                'monday' => 1,
                'tuesday' => 0,
                'wednesday' => 1,
                'thursday' => 0,
                'friday' => 0,
                'saturday' => 0,
                'sunday' => 0,
                'start_date' => '2021-07-09',
                'end_date' => '2022-07-31',
                'created_at' => '2021-07-06 23:05:36',
                'updated_at' => '2021-07-06 23:05:36',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Mardi, jeudi et vendredi',
                'monday' => 0,
                'tuesday' => 1,
                'wednesday' => 0,
                'thursday' => 1,
                'friday' => 1,
                'saturday' => 0,
                'sunday' => 0,
                'start_date' => '2021-07-09',
                'end_date' => '2022-07-31',
                'created_at' => '2021-07-07 13:46:05',
                'updated_at' => '2021-07-07 13:46:05',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Tous les jours',
                'monday' => 1,
                'tuesday' => 1,
                'wednesday' => 1,
                'thursday' => 1,
                'friday' => 1,
                'saturday' => 1,
                'sunday' => 1,
                'start_date' => '2021-07-09',
                'end_date' => '2022-07-31',
                'created_at' => '2021-07-07 13:49:31',
                'updated_at' => '2021-07-07 13:49:31',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Samedi et dimanche',
                'monday' => 0,
                'tuesday' => 0,
                'wednesday' => 0,
                'thursday' => 0,
                'friday' => 0,
                'saturday' => 1,
                'sunday' => 1,
                'start_date' => '2021-07-09',
                'end_date' => '2022-07-31',
                'created_at' => '2021-07-07 13:51:37',
                'updated_at' => '2021-07-07 13:51:37',
                'deleted_at' => null,
            ],
        ]);

        DB::table('stops')->insertOrIgnore([
            [
                'id' => 1,
                'name' => "Plage de l'est",
                'lat' => 45.698068,
                'long' => -73.479623,
            ],
            [
                'id'=>2,
                'name' => 'Quai Aimé-Leonard',
                'lat' => 45.608998,
                'long' => -73.639916,
            ],
            [
                'id'=>3,
                'name' => 'Pont Pie IX',
                'lat' => 45.599939,
                'long' => -73.647522,
            ],
            [
                'id'=>4,
                'name' => 'Église Saint-Vincent-De-Paul',
                'lat' => 45.612817,
                'long' => -73.639748,
            ],
            [
                'id'=>5,
                'name' => 'Pont Olivier-Charbonneau',
                'lat' => 45.635736,
                'long' => -73.622392,
            ],

        ]);

        DB::table('routes')->insertOrIgnore([
            [
                'id' => 1,
                'name' => 'Île aux Cerfeuils',
                'area_id'=> 1,
            ],
            [
                'id' => 2,
                'name' => "Île à l'aigle",
                'area_id'=> 1,
            ],
            [
                'id' => 3,
                'name' => 'Île aux Asperges',
                'area_id'=> 1,
            ],
            [
                'id'=>4,
                'name'=>'Pie IX',
                'area_id'=> 1,
            ],
            [
                'id'=>5,
                'name'=>'Olivier-Charbonneau',
                'area_id'=> 1,
            ],
        ]);

        DB::table('route_stops')->insertOrIgnore([
            [
                'route_id' => 1,
                'stop_id' => 1,
                'stop_sequence' => 1,
                'arrival_minutes' => 0,
            ],
            [
                'route_id' => 1,
                'stop_id' => 1,
                'stop_sequence' => 2,
                'arrival_minutes' => 180,
            ],
            [
                'route_id' => 2,
                'stop_id' => 1,
                'stop_sequence' => 1,
                'arrival_minutes' => 0,
            ],
            [
                'route_id' => 2,
                'stop_id' => 1,
                'stop_sequence' => 2,
                'arrival_minutes' => 120,
            ],
            [
                'route_id' => 3,
                'stop_id' => 1,
                'stop_sequence' => 1,
                'arrival_minutes' => 0,
            ],
            [
                'route_id' => 3,
                'stop_id' => 1,
                'stop_sequence' => 2,
                'arrival_minutes' => 60,
            ],
            [
                'route_id'=> 4,
                'stop_id' => 2,
                'stop_sequence' => 1,
                'arrival_minutes' => 0,
            ],
            [
                'route_id'=> 4,
                'stop_id' => 3,
                'stop_sequence' => 2,
                'arrival_minutes' => 20,
            ],
            [
                'route_id'=> 4,
                'stop_id' => 4,
                'stop_sequence' => 3,
                'arrival_minutes' => 40,
            ],
            [
                'route_id'=> 4,
                'stop_id' => 2,
                'stop_sequence' => 4,
                'arrival_minutes' => 60,
            ],
            [
                'route_id'=> 5,
                'stop_id' => 2,
                'stop_sequence' => 1,
                'arrival_minutes' => 0,
            ],
            [
                'route_id'=> 5,
                'stop_id' => 4,
                'stop_sequence' => 2,
                'arrival_minutes' => 15,
            ],
            [
                'route_id'=> 5,
                'stop_id' => 5,
                'stop_sequence' => 3,
                'arrival_minutes' => 25,
            ],
            [
                'route_id'=> 5,
                'stop_id' => 4,
                'stop_sequence' => 4,
                'arrival_minutes' => 45,
            ],
            [
                'route_id'=> 5,
                'stop_id' => 2,
                'stop_sequence' => 5,
                'arrival_minutes' => 60,
            ],
        ]);

        DB::table('boat_inventories')->insertOrIgnore([
            [
                'id' => 1,
                'name' => "Plage de l'est",
                'boat_category_id' => 1,
                'quantity' => 7,
                'created_at' => '2021-07-07 13:43:17',
                'updated_at' => '2021-07-07 13:43:17',
            ],
            [
                'id' => 2,
                'name' => "Plage de l'est",
                'boat_category_id' => 5,
                'quantity' => 7,
                'created_at' => '2021-07-07 13:43:39',
                'updated_at' => '2021-07-07 13:43:39',
            ],
        ]);

        DB::table('trips')->insertOrIgnore([
            [
                'route_id' => 1,
                'service_id' => 1,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '10:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 1,
                'service_id' => 1,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '10:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 1,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '14:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 1,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '14:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 1,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '15:15:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 1,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '15:15:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 1,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '16:45:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 1,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '16:45:00',
                'guided' => 1,
            ],
            [
                'route_id' => 2,
                'service_id' => 2,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '10:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 2,
                'service_id' => 2,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '10:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 2,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '12:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 2,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '12:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 2,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '14:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 2,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '14:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 2,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '15:15:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 2,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '15:15:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 2,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '16:45:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 2,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '16:45:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '10:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '11:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '10:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '12:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '12:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '11:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '14:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '16:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '14:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '15:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '15:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '16:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '10:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '11:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '10:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '11:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '12:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '12:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '14:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '14:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '15:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '16:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '16:00:00',
                'guided' => 3,
            ],
            [
                'route_id' => 3,
                'service_id' => 3,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '15:30:00',
                'guided' => 3,
            ],
            [
                'route_id' => 1,
                'service_id' => 4,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '10:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 1,
                'service_id' => 4,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '10:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '10:30:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '10:30:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '11:45:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '11:45:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '14:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '14:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '15:15:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '15:15:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '16:45:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '16:45:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '16:30:00',
                'guided' => 1,
            ],
            [
                'route_id' => 3,
                'service_id' => 4,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '16:30:00',
                'guided' => 1,
            ],
            [
                'route_id' => 2,
                'service_id' => 4,
                'boat_category_id' => 5,
                'boat_inventory_id' => 2,
                'start_time' => '14:00:00',
                'guided' => 1,
            ],
            [
                'route_id' => 2,
                'service_id' => 4,
                'boat_category_id' => 1,
                'boat_inventory_id' => 1,
                'start_time' => '14:00:00',
                'guided' => 1,
            ],
        ]);
    }
}
