metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "garage:3901"
rpc_secret = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "7vNw3Q5QfzhJGWVI0uAe2cEAXSCd9xwvw4wTQs0jjvQ="
metrics_token = "n9U5YdQWttG6n6oqQXN8r6f68V8f9cc2lATsIQvHn1Q="
