services:
  pgsql:
    image: "postgres:18-alpine"
    restart: unless-stopped
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_replication_slots=10
      - -c
      - max_wal_senders=10
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "./database/schema:/schema"
      - "./docker/pgsql/create-electric-user.sh:/docker-entrypoint-initdb.d/20-create-electric-user.sh:ro"
      - "pgsql:/var/lib/postgresql/data"
    networks:
      - app
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -q -d "$${POSTGRES_DB}" -U "$${POSTGRES_USER}"
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 30s

  electric:
    image: "electricsql/electric:latest"
    restart: unless-stopped
    environment:
      DATABASE_URL: "${ELECTRIC_DATABASE_URL:-postgresql://electric:password@pgsql:5432/database?sslmode=disable}"
      ELECTRIC_SECRET: "${ELECTRIC_API_SECRET:-electric-local-dev-secret-with-32-bytes-minimum}"
      ELECTRIC_INSECURE: "${ELECTRIC_INSECURE:-false}"
    depends_on:
      pgsql:
        condition: service_healthy
    networks:
      - app

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - "redis:/data"
    networks:
      - app
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  gotenberg:
    image: "gotenberg/gotenberg:8-chromium"
    restart: unless-stopped
    environment:
      CHROMIUM_ALLOW_INSECURE_LOCALHOST: true
      CHROMIUM_IGNORE_CERTIFICATE_ERRORS: true
      CHROMIUM_DISABLE_WEB_SECURITY: true
      CHROMIUM_AUTO_START: true
    networks:
      - app

  garage:
    image: "dxflrs/garage:v2.3.0"
    restart: unless-stopped
    command: "/garage -c /etc/garage.toml server --single-node --default-bucket"
    environment:
      GARAGE_DEFAULT_ACCESS_KEY: "${AWS_ACCESS_KEY_ID:-GKb69252a3b0643e8bd08d4cd4}"
      GARAGE_DEFAULT_SECRET_KEY: "${AWS_SECRET_ACCESS_KEY:-9115be9c9e4994306a4176543b0db461f4eb04c5c8a388676d1b57392d0f4e93}"
      GARAGE_DEFAULT_BUCKET: "${AWS_BUCKET:-app}"
    volumes:
      - "./docker/garage/garage.toml:/etc/garage.toml:ro"
      - "garage-meta:/var/lib/garage/meta"
      - "garage-data:/var/lib/garage/data"
    networks:
      - app
    healthcheck:
      test:
        - CMD
        - /garage
        - -c
        - /etc/garage.toml
        - status
      retries: 3
      timeout: 5s

networks:
  app:
    driver: bridge

volumes:
  pgsql:
    driver: local
  redis:
    driver: local
  garage-meta:
    driver: local
  garage-data:
    driver: local
