version: "3"
services:
    quasar:
      build:
        context: .
        dockerfile: Dockerfile
      image: isnotdoge/quasar
      container_name: quasar
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Toronto
      restart: unless-stopped
      ports:
        - "${QUASAR_PORT:-8080}:${QUASAR_PORT:-8080}"
      volumes:
          - ".:/quasarapp"
      networks:
        lrdc:
          ipv4_address: 172.18.0.6
      command: /bin/sh -c "yarn && quasar dev"

networks:
  lrdc:
    external: true