# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json

bucket_definitions:
  user_todos:
    parameters: SELECT request.user_id() AS user_id
    data:
      - SELECT * FROM todos WHERE todos.user_id::text = bucket.user_id
